### ISSUE TITLE
infinite game results in overflow error and no output

### ISSUE THREAD

**Issue by manimino** [shapr/bmnrs#1]
If the code finds an infinite game, sadness will ensue!

To show this, let's use a 3-jacks game that does not terminate as a test case. 

To try it out, replace https://github.com/shapr/bmnrs/blob/main/src/main.rs#L19 with:
```
        let mut g8344 = read_game("---J-----------------------", "---------------------J---J");
```

The result will be:
```
thread 'main' panicked at 'attempt to add with overflow', src/main.rs:78:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by shapr** [comment]
This is fixed in https://github.com/shapr/bmnrs/commit/53cb7ddbd187af6cf80f8526f25833d2c95a787f thanks for the bug report!
